version: 0.0
os: linux
files:
  - source: build/JavaServletHelloWorld
    destination: /tmp/docker/
hooks:
   AfterInstall:
     - location: build/JavaServletHelloWorld/scripts/java_servlet_hello_world-docker-build.sh
       timeout: 1800
